//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffe_Grinder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Coffe_Grinder_DB_Entities : DbContext
    {
        public Coffe_Grinder_DB_Entities()
            : base("name=Coffe_Grinder_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<CoffeeInventory> CoffeeInventories { get; set; }
        public virtual DbSet<CoffeeType> CoffeeTypes { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatuses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_CoffeeInventoryWithTypes> vw_CoffeeInventoryWithTypes { get; set; }
        public virtual DbSet<vw_LowStockAlerts> vw_LowStockAlerts { get; set; }
        public virtual DbSet<vw_OrderDetailsExtended> vw_OrderDetailsExtended { get; set; }
    }
}
